const assert = require("assert");
const fs = require("fs");
const path = require("path");

const rootDir = path.resolve(__dirname, "..");
const appDir = path.join(rootDir, "app");

const files = fs.existsSync(appDir) ? fs.readdirSync(appDir) : [];
const fileSet = new Set(files);

[
  "index.html",
  "index.js",
  "index.css",
  "host.jsx",
  "modal-edit-folder.index.js",
  "modal-edit-style.index.js",
  "modal-export.index.js",
  "modal-help.index.js",
  "modal-settings.index.js",
  "modal-update.index.js",
].forEach((file) => {
  assert(fileSet.has(file), `Missing build artifact: app/${file}`);
});

const topcoatCss = files.filter((file) => /^[a-f0-9]{32}\.css$/.test(file));
assert(topcoatCss.length >= 2, "Missing copied Topcoat theme CSS files");

// ExtendScript's ES3 parser reads `X || Y && Z` as `(X || Y) && Z`. The source
// spells the parentheses out, but the host bundle is generated by UglifyJS, and
// parentheses are not AST nodes, so they are dropped on the way out. Any such
// expression in the shipped host silently means the opposite of the source.
// This is how `_polygonScanlineSpan` lost every scanline span and made each
// selection fall back to the 423 ms legacy sampler. Write the two branches as
// separate statements instead.
const UglifyJS = require("uglify-js");

const hostPath = path.join(appDir, "host.jsx");
const hostAst = UglifyJS.parse(fs.readFileSync(hostPath, "utf8"));
const misparsed = [];
hostAst.walk(
  new UglifyJS.TreeWalker((node) => {
    if (!(node instanceof UglifyJS.AST_Binary) || node.operator !== "||") return;
    if (node.right instanceof UglifyJS.AST_Binary && node.right.operator === "&&") {
      misparsed.push(`app/host.jsx:${node.start.line}: ${node.print_to_string().replace(/\s+/g, " ").slice(0, 120)}`);
    }
  })
);
assert.deepStrictEqual(
  misparsed,
  [],
  "ExtendScript mis-parses these built expressions as (X || Y) && Z: " + misparsed.join(" | ")
);

console.log("build artifact tests passed");
