const assert = require('assert');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const acorn = require('acorn');
const root = path.resolve(__dirname, '..');
const files = {};
function walk(relative) {
  const absolute = path.join(root, relative);
  if (fs.statSync(absolute).isDirectory()) fs.readdirSync(absolute).forEach(name => walk(relative + '/' + name));
  else files[relative] = fs.readFileSync(absolute);
}
['app', 'CSXS', 'icons', 'locale'].forEach(walk);
require('./helpers/loadAppModule')()('app_src/releasePackage.js').validateReleasePackage(files, bytes => crypto.createHash('sha256').update(bytes).digest('hex'), bytes => bytes.toString('utf8'), require('../package.json').version);
for (const flavor of ['legacy', 'modern']) {
  for (const name of ['modal-edit-folder', 'modal-edit-style', 'modal-export', 'modal-help', 'modal-settings', 'modal-update']) {
    assert(Object.keys(files).some(file => new RegExp('^app/' + flavor + '\\.' + name + '\\.[a-f0-9]{12}\\.index\\.js$').test(file)), 'Missing hashed chunk: ' + flavor + '/' + name);
  }
}
Object.keys(files).filter(name => /^app\/(legacy\..*\.js|index\.js)$/.test(name)).forEach(name => {
  acorn.parse(files[name].toString('utf8'), { ecmaVersion: 5 });
});

// ExtendScript's ES3 parser reads `X || Y && Z` as `(X || Y) && Z`. The source
// spells the parentheses out, but the host bundle is generated by UglifyJS, and
// parentheses are not AST nodes, so they are dropped on the way out. Any such
// expression in the shipped host silently means the opposite of the source.
// This is how `_polygonScanlineSpan` lost every scanline span and made each
// selection fall back to the 423 ms legacy sampler. Write the two branches as
// separate statements instead.
const UglifyJS = require("uglify-js");

const hostPath = path.join(root, "app", "host.jsx");
const hostAst = UglifyJS.parse(fs.readFileSync(hostPath, "utf8"));
const misparsed = [];
hostAst.walk(
  new UglifyJS.TreeWalker((node) => {
    if (!(node instanceof UglifyJS.AST_Binary) || node.operator !== "||") return;
    if (node.right instanceof UglifyJS.AST_Binary && node.right.operator === "&&") {
      misparsed.push(`app/host.jsx:${node.start.line}: ${node.print_to_string().replace(/\s+/g, " ").slice(0, 120)}`);
    }
  })
);
assert.deepStrictEqual(
  misparsed,
  [],
  "ExtendScript mis-parses these built expressions as (X || Y) && Z: " + misparsed.join(" | ")
);

assert(Object.keys(files).filter(name => /[a-f0-9]{32}\.css$/.test(name)).length >= 2, 'Missing Topcoat themes');
console.log('Build artifacts, release inventory and ES5 compatibility verified');
